# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/Web-ID/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:recommends
		"Moose",
		"MooseX::Types";
	:requires
		"Any::Moose",
		"Crypt::X509",
		"DateTime",
		"Digest::SHA",
		"List::MoreUtils",
		"MIME::Base64",
		"Mouse",
		"MouseX::Types 0.06",
		"namespace::clean",
		"Path::Class",
		"Plack",
		"RDF::Query",
		"RDF::Trine",
		"Sub::Exporter",
		"URI";
	:test_requires
		"Test::More 0.61"  .

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/Web/ID.pm" .
