# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/Web-Id/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:requires
		"Any::Moose",
		"Carp",
		"Class::Load",
		"constant",
		"Crypt::X509",
		"DateTime",
		"Digest::SHA1",
		"List::MoreUtils",
		"Math::BigInt",
		"MIME::Base64",
		"Mouse",
		"MouseX::Types",
		"parent",
		"Plack::Util",
		"Plack::Util::Accessor",
		"RDF::Query",
		"RDF::Trine",
		"RDF::Trine::NamespaceMap",
		"strict",
		"Sub::Exporter",
		"URI",
		"URI::Escape",
		"utf8";
	:test_requires
		"Test::More 0.61"  .

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/Web/Id.pm" .

# grep -hr '^use ' lib/ | cut -d ' ' -f 2 | sed 's/;//' | sort -u | sed 's/^/"/;s/$/",/'